<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Post extends Model
{
    //
    protected $fillable = ['title', 'content', 'user_id'];

    //与用户的关联关系
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id', 'id')->withDefault(['name' => 'dennis']);
    }

    //与评论的关联关系
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    //与用户的赞的关联关系
    public function zan($user_id)
    {
        return $this->hasOne('App\Zan')->where('user_id', $user_id);
    }
   //与用户赞的关系
    public function zans()
    {
        return $this->hasOne('App\Zan');
    }
   // 与文章专题的关系
    public function topics()
    {
        return $this->belongsToMany('App\Topic', 'posts_topics');
    }

    public function postTopics()
    {
        return $this->hasMany('App\PostsTopics');
    }


    public function scopeTopicNotBy(Builder $query, $topic_id)
    {
        return $query->doesntHave('postTopics', 'and', function ($q) use ($topic_id) {
            $q->where("topic_id", $topic_id);
        });
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('avaiable', function (Builder $builder) {
            $builder->whereIn('status', [0, 1]);
        });
    }
}
